# Generated by Django 3.1.2 on 2020-10-27 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='snippet',
            name='author',
        ),
        migrations.AddField(
            model_name='snippet',
            name='copied_snippet',
            field=models.ManyToManyField(related_name='_snippet_copied_snippet_+', to='snippet.Snippet'),
        ),
    ]
