# Generated by Django 3.1.2 on 2020-10-28 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippet', '0003_snippet_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='copied_snippet',
            field=models.ManyToManyField(blank=True, related_name='_snippet_copied_snippet_+', to='snippet.Snippet'),
        ),
    ]
